name: instrument-classification-legacy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - librosa=0.7.2
  - pip:
      - fastai==1.0.60
      - jupyter
